Fix setup and improve output
Fix checking required application in 'setup' (ruby/gem) and 'update-dockerfiles' (docker-template)
Fix missing usage for both 'setup' and 'update-dockerfile'
Add missing entries in '.gitignore' for 'bundler' files

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+
+function usage()
+{
+  echo \
+"Usage: $0 [OPTIONS]
+
+  Install the requested version of 'docker-template' in your system
+
+Options:
+    -g | --gem                                  Uses GEM instead of Bundler to install 'docker-template'
+"
+# Prints default usage options, from ./env.sh
+  usage_general_options
+}
+
+
 function install_bundler()
 {
   log info "Installing bundler"
@@ -11,14 +27,12 @@ function install_bundler()
 
 function install_docker_template_bundler()
 {
-  log info "Installing docker-template with Bundler"
+  log info "Installation of 'docker-template' with Bundler"
 
   log info "Copying Gemfile [${DIR}/Gemfile -> ${PWD}]"
   cp ${DIR}/Gemfile ./
 
-  if ! $(bundler exec docker-template list) ; then
-    bundler install --path=vendor/bundler
-  fi
+  bundler show docker-template || { bundler install --path=vendor/bundler; log info "'docker-template' installed with Bundler"; }
 
   return
 }
@@ -70,14 +84,9 @@ function setup()
 {
   log info "Executing from ${PWD}"
 
-  if ! gem --version &> /dev/null ; then
-    log error "Ruby or Gem not found. Please install Ruby 2.1+ before proceeding."
-    exit $E_MISSING_DEPENDENCY
-  fi
+  command_exists gem || { log error "Ruby or Gem not found. Please install Ruby 2.1+ before proceeding." ; exit $E_MISSING_DEPENDENCY; }
 
-  if ! bundler &> /dev/null ; then
-    install_bundler
-  fi
+  command_exists bundler || install_bundler
 
   if [ ! "$DOCKER_TEMPLATE" == "gem" ]; then
     install_docker_template_bundler
@@ -107,13 +116,13 @@ for arg in $@; do
       shift
       ;;
 
-    --* | -*)
+    -*)
       # Any remaining / not parsed option (arg starting with '--' | '-') is consider invalid
-      exit_invalid_option $arg
+      exit_invalid_option "$arg"
       ;;
   esac
 done
 
 # set working dir PROJECT_PATH (resolved by ./env.sh) to setup
-cd $PROJECT_PATH
+cd "$PROJECT_PATH"
 setup "$@"
diff --git a/update-dockerfile b/update-dockerfile
--- a/update-dockerfile
+++ b/update-dockerfile
@@ -14,9 +14,7 @@ function usage()
 
 Params:
   REPOSITORIES    List of repositories to update.
-                  If no repositories are given, it updates all available repositories.
-
-Options:"
+                  If no repositories are given, it updates all available repositories."
 
   # Prints default usage options, from ./env.sh
   usage_general_options
@@ -213,12 +211,16 @@ DIR=$(dirname $(readlink -f $0))
 # includes ./env.sh that resolve environment variables and add default functions
 . ${DIR}/env.sh
 
-if $(which docker-template) ; then
+if command_exists docker-template ; then
   DOCKER_TEMPLATE='docker-template'
-else
+elif bundler show docker-template ; then
   DOCKER_TEMPLATE='bundler exec docker-template'
+else
+  log error "Command 'docker-template' not found. Please setup your system first. See README for instructions."
+  exit $E_MISSING_DEPENDENCY
 fi
-log info "docker-template through ${DOCKER_TEMPLATE}"
+
+log info "docker-template running through '${DOCKER_TEMPLATE}'"
 
 REPOSITORIES=
 declare -A REPO_TAGS
@@ -226,7 +228,7 @@ declare -A TAG_ALIASES
 
 for arg in $@; do
   case $arg in
-    --* | -*)
+    -*)
       # Any remaining / not parsed option (arg starting with '--' | '-') is consider invalid
       exit_invalid_option $arg
       ;;
@@ -235,4 +237,10 @@ done
 
 # set working dir PROJECT_PATH (resolved by ./env.sh) to run update
 cd $PROJECT_PATH
+
+if [ ! -f "${PROJECT_PATH}/opts.yml" ]; then
+  log error "Docker-template project not found in \"project path\": ${PROJECT_PATH}"
+  exit $E_REPO_NOTFOUND
+fi
+
 update_repositories "$@"
